// GENERATED FILE PLACEHOLDER — DO NOT hand-write real values here.
//
// This file must be regenerated by running the FlutterFire CLI against
// your actual Firebase project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command will overwrite this file with real DefaultFirebaseOptions
// values for android/ios/web pulled from your Firebase console project.
// Left as a stub here since no Firebase project has been connected yet.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured yet. '
      'Run `flutterfire configure` to generate real values for this project.',
    );
  }
}
